### Ping
GET http://localhost:3003/ping

### AllProducts
GET  http://localhost:3003/


### CreateProducts
POST http://localhost:3003/product
Content-Type: application/json

{
    "id": ,
    "name": ""
    "tags": ""
}